export { default as Header } from './Header/Header'
export { default as Hero } from './Hero/Hero'
export { default as Popular } from './Popular/Popular'
export { default as Gaming } from './Gaming/Gaming'
export { default as Footer } from './Footer/Footer'